# -*- coding: utf-8 -*-
"""OOPS-practice - 13/12/2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXD5HUt9TdvV8lPorbsf3LVK7mCdWjwE

#**Object oriented programming-Python:-**

**Class:-**
"""

# question no 1.

class student:
  def __init__(self,name,marks):
    self.Name=name
    self.Marks=marks

obj=student("Pintu sharma",86)
print(obj.Marks)
print(obj.Name)

# question no 2.

class calculator:

  def add(self,a,b):
    return a+b

c = calculator()
print("SUM=",c.add(10,20))

# question no 3.

class employee:
  def __init__(self,name,salary):
    self.Name=name
    self.Salary=salary
  def employee_info(self):
    print("employee Name:",self.Name)
    print("employee Salary:",self.Salary)

Emp=employee("Pintu nath sharma",70000)
Emp.employee_info()

# question no 4.

class BankAccount:
  def __init__(self,account_holder,balance):
    self.Account_holder=account_holder
    self.Balance=balance

  def deposit(self,amount):
    self.Balance += amount
    print("Deposited balance:",amount)

  def withdraw(self,amount):
    if amount <=  self.Balance:
      self.Balance -= amount
      print("withdraw amount:",amount)
    else :
      print("Insufficient balance !")

  def show_balance(self):
    print("current balance:",self.Balance)

acc = BankAccount("Prashant Kumar Nath",20000)
acc.deposit(30000)
acc.withdraw(40000)
acc.show_balance()

# question no 5.

class rectangle:
  def __init__(self,l,b):
    self.Length = l
    self.Breadth = b
  def area(self):
    return self.Length * self.Breadth
rect1 = rectangle(10,20)
print("Area of rectangle is :",rect1.area())

# question no 6.

class mobile :
  def __init__(self,brand,price):
    self.Brand=brand
    self.Price=price

  def checking_mobile_price(self):
    if self.Price > 20000:
      print("you cannot afford it!")
    else:
      print(" you can afford it.")


m=mobile(" Vivo ",12000)
m.checking_mobile_price()

"""#**Mini Project:- Bank management system**
**concept:- Python OOP(class,Object,Constructor,Methods)**
"""

class BankAccount:
  def __init__(self, holder, balance):
    self.holder = holder
    self.balance = balance

  def deposit(self, amount):
    self.balance += amount
    print("Deposited:", amount)

  def withdraw(self, amount):
    if amount <= self.balance:
      self.balance -= amount
      print("Withdrawn:", amount)
    else:
      print("Insufficient balance!")

  def show_balance(self):
    print("Account holder:", self.holder)
    print("Current balance:", self.balance)


print("----- Welcome to Bank Management system -----")

Name = input("Enter account Holder Name: ")
Balance = int(input("Enter initial Balance: "))

acc = BankAccount(Name, Balance)

while True:
  print("\n1. Deposit")
  print("2. Withdraw")
  print("3. Check Balance")
  print("4. Exit")

  choice = int(input("Enter your choice: "))

  if choice == 1:
    amt = int(input("Enter deposit amount: "))
    acc.deposit(amt)

  elif choice == 2:
    amt = int(input("Enter withdraw amount: "))
    acc.withdraw(amt)

  elif choice == 3:
    acc.show_balance()

  elif choice == 4:
    print("Thank you for using our bank! Visit again.")
    break

  else:
    print("Invalid choice! Try again.")

class student:
  def __init__(self,name,roll_no):
    self.Name=name
    self.Roll_no=roll_no
  def display(self):
    print("Student details:",self.Name,self.Roll_no)


s=student("Pintu nath sharma,",33)
s.display()

class Atm :
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance

  def deposit(self,amount):
      self.balance+=amount
      print("Money deposited to your bank account=",amount)

  def withdraw(self,amount):
    if amount <= self.balance :
      self.balance-=amount
      print("Money witdraw done:",amount)
    else:
      print("Insufficient balance!")

  def show_balance(self):
    print("your remaining balance is: ",self.balance)


acc = Atm("Pintu nath sharma",3000)
acc.deposit(2000)
acc.withdraw(1000)
acc.show_balance()

class safeAtm:
  def __init__(self,name,balance):
    self.name=name
    self.balance=balance

  def deposit(self,amount):
    if amount <= 0 :
      self.balance+=amount
      print("insufficient balance")
    else:
      print("your balance is added",amount)

  def withdraw(self,amount):
    if amount <= 0:
      print("Invalid withdraw amount")
    elif amount>self.balance:
      print("Insufficient balance")
    else:
      self.balance -= amount
      print("you can withdrawa:",amount)

  def show_balance(self):
    print("Remaining balance:",self.balance)

acc=safeAtm("Pintu nath sharma",5000)
acc.deposit(3000)
acc.withdraw(2000)
acc.withdraw(-100)
acc.show_balance()

