# -*- coding: utf-8 -*-
"""Pandas 16.12.2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pn5qQHj7JbCkvMG2lQfyRU2nypNp1dYz

#**How to find Shape in pandas:-**
"""

# Question no 1.

import pandas as pd

data = {

        "Name":["Pintu sharma","Rahul kumar","Prashant kumar"],
        "Marks":[66,70,80]

}

df=pd.DataFrame(data)
print(df.shape)

# Question no 2.

import pandas as pd

data = {

        "A":[10,20,30,40],
        "B":[1,2,3,4]
}
df=pd.DataFrame(data)
print(df)
print(df.shape)

# Question no 3.

import pandas as pd

data= {

       "Marks":[55,88,67,56,55]
}
df=pd.DataFrame(data)
print(df.shape)

# Question no 4.

import pandas as pd

data ={

       "Name":["A","B","C"],
       "Age":[20,21,23],
       "City":["Bhubaneswar","Banglore","Gurgaon"]
}
df = pd.DataFrame(data)
print(df.shape)

#question no 5.

import pandas as pd

data = {
    "X": [1, 2, 3],
    "Y": [4, 5, 6]
}

df = pd.DataFrame(data)
print(df.shape)

"""#**How to add Rows and Column in DataFrame:-**"""

import pandas as pd

data = {

        "Name":["Pintu sharma","Rahul kumar","Prashant mishra"],
        "Marks":[66,70,67]
}
df=pd.DataFrame(data)
df["City"] = ["Banglore","Pune","Bhubaneswar"]
df

# Question no 1.

import pandas as pd

data = {

        "Name":["Pintu","Prashant","Shubham","Rahul","rohit"],
        "Marks":[44,54,76,88,65]
}
df=pd.DataFrame(data)
df["city"] = ["Banglore","Delhi","Pune","Bhubaneswar","Gurgaon"]
df

# Question no 2.

import pandas as pd

data = {

        "Name":["Pintu","shubham","Shubhankar","Abhisekh"],
        "Marks":[44,54,55,78,],
        "City":["Banglore","Pune","Bhubaneswar","Jajpur town"]
}
df = pd.DataFrame(data)
df["Passed"]=True
df

"""#**Adding column in middle of the DataFrame:-**"""

# Code example

import pandas as pd

df = pd.DataFrame({

                   "Name":["Pintu","Laxman","dhurva"],
                   "Marks":[33,45,60]
})
df.insert(1,"City",["Banglore","Pune","Kharagpur"])
df

# Question no 1.

import pandas as pd

df = pd.DataFrame({

                   "student":["Amit","Neha","Rohit","Sneha"],
                   "Score":[72,85,64,90]
})
print(df)
df.insert(1,"City",["Delhi","Mumbai","Pune","kolkata"])
df

# Question no 2.

df = pd.DataFrame({

                   "Name":["Hritik","Piyus","Abhilas","Chandan"],
                   "School":["KV","KV","APEX","SSVM"]
})
df.insert(0,"Roll no",[201,202,203,204])
df

# Question no 3.

import pandas as pd

df = pd.DataFrame({

                   "Name":["Mohit","Ansh","Abraham","Romiti"],
                   "Vehicle":["Bullet","R15","Access","Supra"]
})
print(df.columns)
print(df)

"""#**How to add rows in DataFrame**"""

# Code example.

import pandas as pd

df = pd.DataFrame({

                   "Name":["Pintu","mohit","Ansh","Devansh"],
                   "Vehicle":["Bullet","Pulsar","Hero Honda","Supra"]
})

df.loc[4] = ["Sneha","Activa"]
df

# Question no 1.

import pandas as ps

df = pd.DataFrame({

                   "Name":["Pintu","Sneha","Rakesh","Laxmi"],
                   "Gender":["Male","Female","Male","Female"]
})
print(df)
df.loc[4]=["Ritu","Female"]
df

# Question no 2.

import pandas as pd

df = pd.DataFrame({
    "Name":["Mohit","Abraham","Ansh","Romiti"],
    "Vehicle":["Bullet","R15","Access","Supra"]

})
df.loc[5] =["Rahul","Pulsar"]
print(df)

"""#**How to remove rows and column in DataFrame:-**"""

# code example .

import pandas as pd

df = pd.DataFrame({

                   "Name":["Pintu","Prashant","Ahil"],
                   "Roll":[33,45,43]
})
df = df.drop("Roll",axis=1)
print(df)

# code example 2 .

import pandas as pd

df = pd.DataFrame({

                   "Employee":["Ravi","Kunal","Sita","Meena"],
                   "Department":["HR","IT","Finance","IT"],
                   "Salary":[30000,45000,40000,48000],
                   "City":["Delhi","Pune","Mumbai","Banglore"]
})
print("Original DataFrame:")
print(df)

df = df.drop("City",axis=1)
print("After removing city column:")
print(df)

"""**Removing multiple rows**"""

# code example 3 .

import pandas as pd

df = pd.DataFrame({

                   "Employee":["Ravi","Kunal","Sita","Meena"],
                   "Department":["HR","IT","Finance","IT"],
                   "Salary":[30000,45000,40000,48000],
                   "City":["Delhi","Pune","Mumbai","Banglore"]
})

df = df.drop(["Department", "Salary"],axis=1)
print(df)

import pandas as pd

df = pd.DataFrame({

                   "Employee":["Ravi","Kunal","Sita","Meena","Aman"],
                   "Department":["HR","IT","Finance","IT","HR"],
                   "salary":[30000,45000,40000,48000,35000],
                   "City":["Delhi","Pune","Mumbai","Banglore","Delhi"],
                   "Experience":[2,4,3,5,1]
})
df

print("After removing Department and city:")
new_df=df.drop(["Department","City"],axis=1)
print(new_df)

print("After removing salary:")
df1=df.drop(["salary"],axis=1)
print(df1)

print("After removing Experience and salary:")
df2 = df.drop(["Experience","salary"],axis=1)
print(df2)

print("After removing Employee and salary:")
df3=df.drop(["Employee","City"],axis=1)
print(df3)

print("After removing Department ,salary and Experience")
df4=df.drop(["Department","salary","Experience"],axis=1,inplace=True)
print(df4)

"""#**Concatenate:-**"""

import pandas as pd

df1 = pd.DataFrame({

                   "Name":["Pintu","Rakesh","Samsher"],
                   "Grad":["B-Tech","BCA","MBA"]
})

df2 = pd.DataFrame({

                    "Name":["Rahul","Prashant","Lokesh","Ankit"],
                    "Gard":["BA","BSC","B-Tech","Diploma"]
})
pd.concat([df1,df2],ignore_index=True)

import pandas as pd

df1 = pd.DataFrame({

                   "Name":["Pintu","Satyam","Shubham","Rahul"],
                   "Course":["AI","ML","DA","DS"]
})

df2=pd.DataFrame({

                  "Name":["Ramesh","Rakesh","Rohit","Somesh"],
                  "Course":["CHM hnrs","PHY hnrs","ENG hnrs","MATHShnrs"]
})
pd.concat([df1,df2],ignore_index=True)

"""#**Analysing the data:-**
**Describe**
"""

import pandas as pd

df = pd.DataFrame({

                   "Marks":[40,50,43,44,34,67,55]
})
print(df.describe())

import pandas as pd

df = pd.DataFrame({
    "A":[22,36,78,65,44]
})
print(df.describe())