# -*- coding: utf-8 -*-
"""Pandas - 15/12/2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKBEP4cfkNQR_RAotUJzyf1KwpxbmRZc

#**PANDAS**
"""

import pandas as pd

print(pd.__version__)

"""#**Series:-**"""

import pandas as pd

l= [1,2,3,4,5]
s= pd.Series(l)
print(s)

s=pd.Series(["Name",20,"Male","Tech"])
print(s)

s=pd.Series(["Apple","banana","cherry","mango"],index=["A","B","C","D"])
print(s)

gender=pd.Series(["Male","Female","Female","Male","Female"],index=["A","B","C","D","E"])
print(gender)
print(type(gender))

d = {

     "A":90,
     "B":93,
     "C":75,
     "D":72,
     "E":95
}
marks=pd.Series(d)
marks

d = {

     "A":90,
     "B":93,
     "C":75,
     "D":72,
     "E":95
}
marks=pd.Series(d,index=["A",2,"C","D",3])
marks

import pandas as pd

s = pd.Series([85, 90, 78], index=["Amit", "Rahul", "Neha"])
print(s)
print(s.index)

"""#**Series with dictionaries:-**"""

# Basic code example.

data = {

        "a":10,
        "b":20,
        "c":30
}

s = pd.Series(data)
s

# real world example.

marks={

       "maths":85,
       "physics":78,
       "chemistry":88
}
marks_series=pd.Series(marks)
print(marks_series)

#Question no 1.

import pandas as pd

data = {

        "x":5,
        "y":10,
        "z":15
}
s=pd.Series(data)
print(s)

#Question no 2.

import pandas as pd

data = {

        "x":5,
        "y":10,
        "z":15
}
s=pd.Series(data)
print(s["y"])

# Question no 3.

import pandas as pd

marks ={

        "English":72,
        "Maths":90,
        "Science":85
}
s=pd.Series(marks)
print(s)

print(s["Maths"])

#question no 4.

import pandas as pd

data = {

        "CS":88,
        "IT":92,
        "Math":80,
        "Physics":75
}
s=pd.Series(data,index=["CS","Math"])
print(s)

# Question no 5.

import pandas as pd

population = {

              "Odisha":45000000,
              "Bihar":124000000,
              "Wb":99000000
}
s = pd.Series(population)
print(s)
print(s.values)

data=[5,10,15,2]
s=pd.Series(data)
print(s)
print(s.index)

l=["Apple","Banana","Orange","Pineapple","Strawberry"]
s=pd.Series(l,index=["a","b","c","d","e"])
print(s)
print(s["c"])

"""#**Data frames:-**
**They are two dimensional collection of data.**

**They tables,with rows and coloumns**
"""

data={

      "Name":["A","B","C","D"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64]
}
df=pd.DataFrame(data)
df

data={

      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64]
}
df=pd.DataFrame(data,index=['a','b','c','d'])
print(df)

import pandas as pd

data = {

        "Roll":[1,2,3],
        "Name":["Pintu","Aman","Rohit"],
        "Marks":[85,78,90]
}

df=pd.DataFrame(data)
df

import pandas as pd

data = [10,20,30,40]
s=pd.DataFrame(data,columns=["Numbers"])
print(s)

data = [[1,"Pintu",78],
        [2,"Rahul",78],
        [3,"Aman",90]]
s=pd.DataFrame(data,columns=["Roll","Name","Marks"])
df

data = {

        "Name":["Pintu","Satyam","Aman"],
        "Marks":[85,78,99]
}
s = pd.DataFrame(data)
print(df)
df

import pandas as pd

data = {

        "Name":["Pintu","Rahul","Sambit","Satabdi"],
        "City":["Banglore","Bhubaneswar","Jajpur Town","Cuttack"],
        "Marks":[40,50,55,33]
}
df=pd.DataFrame(data)
print(df)
print(df.loc[1])
print(df.iloc[1:])

import pandas as pd

data = {

        "Name":["Pintu","Rahul","Sambit","Satabdi"],
        "City":["Banglore","Bhubaneswar","Jajpur Town","Cuttack"],
        "Marks":[40,50,55,33]
}
df = pd.DataFrame(data)
print(df.loc[1])

data = {

        "Name":["Pintu","Rahul","Sambit","Satabdi"],
        "City":["Banglore","Bhubaneswar","Jajpur Town","Cuttack"],
        "Marks":[40,50,55,33]
}
df=pd.DataFrame(data)
print(df.loc[2,"Marks"])

data = {

        "Name":["Pintu","Rahul","Sambit","Satabdi"],
        "City":["Banglore","Bhubaneswar","Jajpur Town","Cuttack"],
        "Marks":[40,50,55,33]
}
df=pd.DataFrame(data)
print(df.loc[0,["Name","City"]])

import pandas as pd

data = {
    "Name": ["Pintu", "Rahul", "Sambit", "Satabdi", "Aman"],
    "Maths": [60, 55, 70, 40, 85],
    "Science": [65, 50, 72, 45, 90],
    "City": ["Bangalore", "Delhi", "Cuttack", "Kolkata", "Mumbai"]
}

df = pd.DataFrame(data)
print(df.iloc[-2:])

"""#**Accessing Rows and Coloumns**"""

data={

      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}
df=pd.DataFrame(data)
df
print(df["Name"])

data={

      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}
df=pd.DataFrame(data)
df
print(df[["Name","Marks"]])

"""**Access Rows**

#**loc**
"""

data={

      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}

df=pd.DataFrame(data,index=['a','b','c','d'])
print(df.loc[['a','b']])

"""#**Slicing using loc and Iloc:-**"""

data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}
df=pd.DataFrame(data)
df
print(df.loc[[0,2,3],["Roll","Gender","Name"]])

data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}
df=pd.DataFrame(data)
df
print(df.iloc[-3:,[1,3]])

df=pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df)

"""#**Heads**"""



"""#**tail**"""



import pandas as pd


data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}

df=pd.DataFrame(data)
print(df)

df["section"]=["A","A","B","D"]
print(df)

df.insert(1,"School",["ABC","KV","APS","apex"])
print(df)

data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}

df.insert(6,"sports",["Race","High jump","Long jump","javlin throw"])
print(df)

Dict = {"name":["pintu","satyam","subham"],
       "school":["KV","APEX","DELHI PUBLIC"],
      "Roll no":[12,11,23]}
df1 = pd.DataFrame(Dict)
print(df1)
new=pd.concat([data,Dict])
print(new)

data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}

df1 = pd.DataFrame(data)
print(df1)
new=pd.concat([data,Dict])
print(new)

data = {


      "Name":["Ayush","Baljeet","Charan","Dhruv"],
      "Roll":[22,12,45,37],
      "Marks":[88,75,91,64],
      "Gender":["Male","Female","Male","Female"]
}

df = pd.DataFrame(data)
print(df)
df.drop(0,axis=0,inplace=True)
print(df)

import seaborn as sb

data = sb.load_dataset("titanic")
df=pd.DataFrame(data)
print(df)

print(df.head())
print(df.head(7))

print(df.info())

print(df.describe())

print(df["age"].mean())
print(df["age"].max())

print(df.head())

print(df["class"].unique())

print(df["class"].nunique())

print(df["class"].value_counts())

print(df.isna().sum().sum())

